# Makefile fragment for the cuda extension.
#
# The PHP build system only knows how to compile C sources. CUDA (.cu) files
# are compiled here with NVCC into plain object files, which are then:
#   1. built as prerequisites of the `all` target (the module target name is
#      generated by the build system and not stable enough to reference), and
#   2. appended to the link line via EXTRA_LDFLAGS (set in config.m4).
#
# Note: PHP_ADD_MAKEFILE_FRAGMENT sed-replaces $(srcdir)/$(builddir) with
# absolute paths when appending this file, so do not rely on those variables
# for target names.

NVCC_OBJECTS = \
	cuda_kernels.o \
	tensor_kernels.o \
	memory_pool.o \
	memory_utils.o \
	cpu_ops.o \
	tensor_core_ops.o \
	profiler.o

# conv_ops.o is appended by config.m4 (via CUDNN_EXTRA_OBJECTS/EXTRA_LDFLAGS)
# only when cuDNN is enabled; the pattern rule below compiles it the same way.

%.o: %.cu
	$(NVCC) $(NVCC_FLAGS) -I$(top_srcdir) -c $< -o $@

# Recipe-less rules: the NVCC objects must be prerequisites of the module
# target itself, otherwise a parallel make races the link against the NVCC
# compilations. The generated module target is named "./cuda.la" on current
# PHP build systems; both spellings are listed for robustness.
./cuda.la cuda.la: $(NVCC_OBJECTS) $(CUDNN_EXTRA_OBJECTS)

clean-cuda:
	rm -f $(NVCC_OBJECTS) conv_ops.o

.PHONY: clean-cuda
